import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Manu App</title>
        <meta name="description" content="Generated by create manu app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen w-screen flex justify-center items-center">Ready to code</main>
    </>
  );
}
