import Head from 'next/head';
import { ReactNode } from 'react';

import Header from '@/components/Header';
import Footer from '@/components/Footer';

type PageProps = {
  title: string;
  children: JSX.Element | JSX.Element[] | ReactNode;
  className?: string;
  footer?: boolean;
};

export default function PageLayout({ title, children, className, footer = true }: PageProps) {
  const isPreviewEnv = process.env.NEXT_PUBLIC_PREVIEW_MODE === 'true';

  const pageTitle = `${isPreviewEnv ? 'Preview | ' : ''}MaxWood | ${title}`;

  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create manu app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen flex flex-col">
        <Header />
        <main className={`flex-1 mt-16 ${className || ''}`}>{children}</main>
        {footer && <Footer />}
      </div>
    </>
  );
}
